### ISSUE TITLE
Error: callEnigmaWebAPI: http status: 412 - check webinterface settings

### ISSUE THREAD

**Issue by xantam23** [mdaskalov/homebridge-dreambox#35] opened 2021-10-28 22:18 UTC
Hi,

all I get in the logs of homebridge are:

[10/29/2021, 12:13:23 AM] [Dreambox] 192.168.0.3 :- callEnigmaWebAPI: http status: 412 - check webinterface settings
[10/29/2021, 12:13:23 AM] [Dreambox] 192.168.0.3 :- callEnigmaWebAPI: http status: 412 - check webinterface settings
[10/29/2021, 12:13:53 AM] [Dreambox] 192.168.0.3 :- callEnigmaWebAPI: http status: 412 - check webinterface settings
[10/29/2021, 12:13:53 AM] [Dreambox] 192.168.0.3 :- callEnigmaWebAPI: http status: 412 - check webinterface settings
[10/29/2021, 12:14:23 AM] [Dreambox] 192.168.0.3 :- callEnigmaWebAPI: http status: 412 - check webinterface settings
[10/29/2021, 12:14:23 AM] [Dreambox] 192.168.0.3 :- callEnigmaWebAPI: http status: 412 - check webinterface settings

I'm running a dm900 with latest OE2.5 Experimental Image.

`{
    "devices": [
        {
            "name": "dm900",
            "hostname": "192.168.0.3",
            "port": 80,
            "bouquet": "Favoriten",
            "updateInterval": 0,
            "offWhenUnreachable": true
        }
    ],
    "platform": "Dreambox"
}`

**Comment by mdaskalov** [comment] 2021-11-01 10:34
Seems that the problem is solved... will close it.

**Closed by mdaskalov** 2021-11-01 10:34 UTC
